### ISSUE TITLE
Bug _guts.xml does not work with filehive

### ISSUE THREAD

**Issue by icaHWI** [icarus-consulting/Xive#116]
### Expected Behavior

The _guts.xml works with the filehive
### Actual Behavior

The xmlInFiles tries to parse all files as a xml also the files that are no xml
### Mention any other details that might be useful

The XmlInFiles tries to parse the catalog.cat as xml because the xmlInFiles.Knowledge() returns all data including files that are no xml.

The xmlInFiles need to save the files that are xml files like the XmlInRam. Otherwise we dont know if the file is last accessed via Xocument or via Cell

**Comment by Meerownymous** [comment]
Seems legit, the catalog.cat was introduced without regarding the Knowledge method. 
This can be solved like suggested. Is there any other question?
