### ISSUE TITLE
First Node Of Xocument has to be named after the xocument

### ISSUE THREAD

**Issue by jaanpeeter** [icarus-consulting/Xive#169]
### Expected Behavior

The first node can have another name than the xocument
### Actual Behavior

The  root node can not have another name than the xocument
Fails with:
Yaapii.Xambly.Error.IllegalStateException: 'quietly failed to apply DOM: ADDIF anothername;'
ImpossibleModificationException: Exception at dir 1: ADDIF anothername(This operation would create an incorrectly structured document.)

### Steps to reproduce the behavior

            row.Xocument("name").Modify(
               new Directives().AddIf("anothername")
               );

**Comment by Meerownymous** [comment]
There is a misunderstanding of the error message: In the provided code snippet, a second node is added to the root of the xml document. Xml documents can only have one node at root level.

**Comment by jaanpeeter** [comment]
Thanks for clarifying
