### ISSUE TITLE
New files should have modify ACL for Domain Users

### ISSUE THREAD

**Issue by jussen** [icarus-consulting/Xive#98]
### Expected Behavior

Read/Write permission for Domain Users or (in case there isn't a domain controller defined) Authenticated Users.

### Actual Behavior

Only the creator gets the modify permission. 

### Mention any other details that might be useful

By default, each new file in Windows OS gets the expected behavior as described above. Please verify for Workgroup users.
https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems

**Comment by jussen** [comment]
Should be implemented in the release which is used in the DopX repo.

**Comment by Meerownymous** [comment]
Update: New files will inherit their permissions from the parent folder.

**Comment by Meerownymous** [comment]
This issue is obsolete. Investigation had the result that the xive already behaves this way - it inherits the folder permissions of its root folder.
